# Generated by Django 4.1.4 on 2023-01-30 00:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dms", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chattingroom",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="chattingroom",
            name="sender",
        ),
        migrations.AddField(
            model_name="chattingroom",
            name="user",
            field=models.ManyToManyField(
                related_name="chatting_rooms", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
