# Generated by Django 4.1.4 on 2023-01-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_address_alter_user_detailed_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="user",
            name="detailed_address",
            field=models.CharField(default="", max_length=250),
        ),
    ]
