# Generated by Django 4.1.4 on 2023-01-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("price", models.IntegerField()),
                ("description", models.TextField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("electronics", "Electronics"),
                            ("furnitures", "Furnitures"),
                            ("kitchen", "Kitchen"),
                            ("clothes", "Clothes"),
                            ("tickets", "Tickets"),
                            ("plants", "Plants"),
                            ("etc", "Etc"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_reported", models.BooleanField(default=False)),
                ("is_sold", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
