# Generated by Django 4.1.4 on 2023-01-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
